@baseUrl = http://localhost:3000/api
@authToken = {{loginCustomer.response.body.token}}

### Test if Customer service is up
GET {{baseUrl}}/customer/health
# Expected: { "status": "Customer service is running" }

### Login as Customer
# @name loginCustomer
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "password123"
}


### Get Customer Orders (Protected)
GET {{baseUrl}}/customer/orders
Authorization: Bearer {{authToken}} 